[package]
name = "goannaservo"
version = "0.0.0"
authors = ["nobody@mozilla.org"]
license = "MPL-2.0"
description = "Dummy goannaservo package for build-time bindgen to land turned off"

[features]
bindgen = []

[lib]
path = "lib.rs"
